// arranger.ts — auto-evolving arrangement. Every `sectionBars` cycles a new 16-bar section
// is derived; a 5-stage macro arc (intro→build→develop→climax→resolve) advances every
// `stageBars` cycles. The development is generated by COMBINING factors (climate / current /
// soil / weather) through a chosen ENGINE (plant growth / physics oscillation / geometry
// quantisation) — a huge deterministic space of variations. Timbre is NOT touched here.
import type { ParamState } from "../core/params";
import type { Composer } from "./composer";

export const ENGINES = ["PLANT", "PHYSICS", "GEOMETRY"] as const;
export const CLIMATES = ["tropical", "temperate", "arid", "polar"] as const;
export const CURRENTS = ["warm", "cold", "gyre", "upwelling"] as const;
export const SOILS = ["sand", "clay", "loam", "volcanic"] as const;
export const WEATHERS = ["clear", "rain", "storm", "fog"] as const;

const FAMILIES = ["MANDALA", "KILIM", "GIRIH", "KNOT", "KOLAM"];
const PALETTES = ["indigo", "jewel", "earth", "ochre", "mono", "sunset"];

const CLIMATE_V: Record<string, number> = { tropical: 0.9, temperate: 0.55, arid: 0.4, polar: 0.15 };
const CURRENT_V: Record<string, number> = { warm: 0.7, cold: 0.3, gyre: 0.5, upwelling: 0.85 };
const SOIL_V: Record<string, number> = { sand: 0.3, clay: 0.6, loam: 0.78, volcanic: 0.92 };
const WEATHER_V: Record<string, number> = { clear: 0.4, rain: 0.6, storm: 0.9, fog: 0.25 };

const SOIL_FAMILY: Record<string, string> = { sand: "MANDALA", clay: "KILIM", loam: "KOLAM", volcanic: "GIRIH" };
const CLIMATE_PAL: Record<string, string> = { tropical: "jewel", temperate: "earth", arid: "ochre", polar: "indigo" };
const WEATHER_PAL: Record<string, string> = { clear: "ochre", rain: "indigo", storm: "sunset", fog: "mono" };

const STAGE_E = [0, 0.2, 0.45, 0.7, 1.0, 0.4]; // 1-indexed
const SPARSE = ["waltz", "dadra", "aksak7", "straight8", "rupak"];
const MIDR = ["jhaptal", "tresillo", "maqsum", "baladi", "aksak9", "ektal"];
const BUSY = ["teental", "sonClave", "bembe", "aksak11", "lancaran", "ayoub", "straight16"];

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => { a |= 0; a = (a + 0x6d2b79f5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
}
function hash(s: string): number { let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }
const clamp = (v: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, v));

export interface Factors { engine: string; climate: string; current: string; soil: string; weather: string }
export interface SectionInfo { stage: number; section: number; rhythmChanged: boolean }

export class Arranger {
  stage = 1;
  section = 0;
  private lastSec = -1;

  // Call each cycle. Returns non-null when a new section was applied to `state`.
  update(cycle: number, state: ParamState, composer: Composer, f: Factors): SectionInfo | null {
    const sectionBars = Math.max(1, Math.round(state.sectionBars as number));
    const stageBars = Math.max(1, Math.round(state.stageBars as number));
    const sec = Math.floor(cycle / sectionBars);
    if (sec === this.lastSec) return null;
    this.lastSec = sec;
    this.section = sec;
    this.stage = 1 + (Math.floor(cycle / stageBars) % 5);
    const prevRhythm = state.rhythmId as string;
    this.derive(state, composer, f, sec, this.stage);
    return { stage: this.stage, section: sec, rhythmChanged: (state.rhythmId as string) !== prevRhythm };
  }

  private derive(state: ParamState, c: Composer, f: Factors, sec: number, stage: number): void {
    const rng = mulberry32(hash(`${f.engine}|${f.climate}|${f.current}|${f.soil}|${f.weather}|${sec}`));
    const energy = STAGE_E[stage];
    const cV = CLIMATE_V[f.climate], curV = CURRENT_V[f.current], soV = SOIL_V[f.soil], weV = WEATHER_V[f.weather];

    // common mix / space
    state.reverbMix = clamp(0.12 + weV * 0.3, 0, 1);
    state.chordLevel = clamp(0.3 + soV * 0.2, 0, 1);
    state.riffLevel = clamp(0.35 + energy * 0.3, 0, 1);
    state.soloLevel = clamp(0.35 + energy * 0.35, 0, 1);
    state.chordOn = true;
    state.riffOn = stage >= 2;
    state.soloOn = stage >= 2 && energy > 0.35;

    let bpm: number, chordEvery: number, soloDensity: number, sym: number;
    let family: string, palette: string, moveBias: number, baseShift: number, speed: number, morph: number;

    if (f.engine === "PHYSICS") {
      const osc = 0.5 + 0.5 * Math.sin(sec * 0.9 + curV * 6.283);
      const e2 = energy * (0.55 + 0.45 * osc);
      bpm = 78 + curV * 48 + osc * 26;
      chordEvery = clamp(1 + Math.round(osc * 3), 1, 4);
      soloDensity = clamp(0.25 + 0.55 * osc * cV + 0.2 * e2, 0, 1);
      sym = 4 + Math.round(curV * 6);
      family = FAMILIES[Math.floor(osc * 4.99)];
      palette = WEATHER_PAL[f.weather];
      moveBias = clamp(0.4 + osc * 0.5, 0, 1);
      baseShift = Math.round((osc - 0.5) * 4);
      speed = 0.3 + osc * 0.8;
      morph = clamp(0.3 + e2 * 0.6, 0, 1);
    } else if (f.engine === "GEOMETRY") {
      sym = 3 + (sec % 8);
      bpm = 84 + (sec % 5) * 12 + (stage - 1) * 6;
      chordEvery = [1, 2, 4, 2, 1][sec % 5];
      soloDensity = [0.3, 0.55, 0.85, 0.5, 0.4][(sec + stage) % 5];
      family = FAMILIES[sec % 5];
      palette = PALETTES[(sec + Math.floor(soV * 3)) % 6];
      moveBias = [0.2, 0.6, 0.9, 0.5][sec % 4];
      baseShift = [0, 2, 4, -3, 0][sec % 5];
      speed = 0.2 + (sym / 12) * 0.6;
      morph = clamp(0.2 + energy * 0.4, 0, 1);
    } else { // PLANT — growth / branching
      const g = 0.15 + 0.85 * (stage / 5);
      bpm = 66 + cV * 60 + energy * 16 + (rng() - 0.5) * 6;
      chordEvery = clamp(Math.round(4 - 3 * g), 1, 4);
      soloDensity = clamp(0.2 + 0.45 * cV + 0.3 * curV * energy, 0, 1);
      sym = 5 + Math.round(soV * 4);
      family = SOIL_FAMILY[f.soil];
      palette = CLIMATE_PAL[f.climate];
      moveBias = clamp(0.3 + g * 0.5, 0, 1);
      baseShift = stage >= 4 && rng() < 0.5 ? c.scale.cents.length - 3 : 0;
      speed = 0.2 + curV * 0.6;
      morph = clamp(0.25 + energy * 0.6, 0, 1);
    }

    // rhythm pool by overall drive (geometry picks deterministically)
    const drive = energy * 0.6 + cV * 0.4;
    const pool = drive < 0.4 ? SPARSE : drive < 0.7 ? MIDR : BUSY;
    state.rhythmId = f.engine === "GEOMETRY" ? pool[sec % pool.length] : pool[Math.floor(rng() * pool.length)];

    state.bpm = clamp(Math.round(bpm), 40, 220);
    state.chordEvery = chordEvery;
    state.soloDensity = soloDensity;
    state.symmetry = clamp(Math.round(sym), 3, 12);
    state.patternFamily = family;
    state.palette = palette;
    state.morphAmt = morph;
    state.patternSpeed = clamp(speed, 0, 2);
    c.moveBias = moveBias;
    c.baseShift = baseShift;
  }
}
